export const StockDataTypes = {
	SET_INPUT_FIELD: 'SET_INPUT_FIELD',
	SET_COLUMNS: 'SET_COLUMNS',
	DELETE_ROW: 'DELETE_ROW',
	DELETE_ALL_ROWS: 'DELETE_ALL_ROWS',
	ADD_ROW: 'ADD_ROW',
	SET_ROW: 'SET_ROW',
	SET_ROWS: 'SET_ROWS',
	SET_ALL_INTERVALS: 'SET_ALL_INTERVALS',
	ADD_UNIVERSE: 'ADD_UNIVERSE',
	UPDATE_NON_CUSTOM_INDICATORS: 'UPDATE_NON_CUSTOM_INDICATORS',
	DAILY_UPDATE: 'DAILY_UPDATE',
};
