export const ConfigurationTypes = {
	SET_CHART_INDICATOR_CONFIGURATION: 'SET_CHART_INDICATOR_CONFIGURATION',
	SET_CHART_INDICATORS: 'SET_CHART_INDICATORS',
	DELETE_CHART_INDICATOR: 'DELETE_CHART_INDICATOR',
	ADD_CHART_INDICATOR: 'ADD_CHART_INDICATOR',
};
